name: rustup toolchain install
author: David Tolnay
description: Install the Rust toolchain
branding:
  icon: activity
  color: purple

inputs:
  toolchain:
    description: Rust toolchain specification -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
    required: true
  target:
    description: Target triple to install for this toolchain
    required: false
  components:
    description: Comma-separated list of components to be additionally installed
    required: false

outputs:
  version:
    description: Version as reported by `rustc --version`, e.g. "rustc 1.62.0 (a8314ef7d 2022-06-27)"
    value: ${{steps.rustc-version.outputs.version}}
  commit-hash:
    description: The rustc source revision, e.g. "a8314ef7d0ec7b75c336af2c9857bfaf43002bfc"
    value: ${{steps.rustc-version.outputs.commit-hash}}
  abbrev-hash:
    description: The abbreviated rustc source revision, e.g. "a8314ef7d"
    value: ${{steps.rustc-version.outputs.abbrev-hash}}
  commit-date:
    description: The rustc source date, e.g. "2022-06-27"
    value: ${{steps.rustc-version.outputs.commit-date}}
  release:
    description: The rustc version, e.g. "1.62.0"
    value: ${{steps.rustc-version.outputs.release}}

runs:
  using: composite
  steps:
    - id: flags
      run: |
        : construct rustup command line
        echo "::set-output name=targets::$(for t in ${targets//,/ }; do echo -n ' --target' $t; done)"
        echo "::set-output name=components::$(for c in ${components//,/ }; do echo -n ' --component' $c; done)"
        echo "::set-output name=downgrade::${{inputs.toolchain == 'nightly' && inputs.components && ' --allow-downgrade' || ''}}"
      env:
        targets: ${{inputs.target}}
        components: ${{inputs.components}}
      shell: bash
    - run: |
        : install rustup if needed
        if ! command -v rustup &> /dev/null ; then
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          echo "${CARGO_HOME:-~/.cargo}/bin" >> $GITHUB_PATH
        fi
      if: runner.os != 'Windows'
      shell: bash
    - name: rustup toolchain install ${{inputs.toolchain}}
      run: rustup toolchain install ${{inputs.toolchain}}${{steps.flags.outputs.targets}}${{steps.flags.outputs.components}} --profile minimal${{steps.flags.outputs.downgrade}} --no-self-update
      shell: bash
    - run: rustup default ${{inputs.toolchain}}
      shell: bash
    - id: rustc-version
      run: |
        echo "::set-output name=version::$(rustc --version)"
        echo "::set-output name=commit-hash::$(rustc --verbose --version | sed -ne 's/commit-hash: //p')"
        echo "::set-output name=abbrev-hash::$(rustc --verbose --version | sed -ne 's/commit-hash: //p' | head -c9)"
        echo "::set-output name=commit-date::$(rustc --verbose --version | sed -ne 's/commit-date: //p')"
        echo "::set-output name=release::$(rustc --verbose --version | sed -ne 's/release: //p')"
      shell: bash
    - run: rustc --verbose --version
      shell: bash
