name: 'rustup toolchain'
description: 'Install the Rust toolchain'
author: 'actions-rs team'
branding:
  icon: play-circle
  color: black
inputs:
  toolchain:
    description: |
      Rust toolchain name.

      See https://github.com/rust-lang/rustup.rs#toolchain-specification
    required: true
  default:
    description: Set installed toolchain as default
    default: false
  override:
    description: Set installed toolchain as an override for a directory
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'
