name: Repro

on:
  push:
    branches: [repro]

permissions:
  contents: read

jobs:
  repro:
    name: Repro
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - run: echo 1.85.0 > rust-toolchain
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
